global:
  scrape_interval: 15s #internal pengambilan data

scrape_configs:
  - job_name: 'prometheus' # monitoring diri sendiri
    static_configs: 
    - targets: ['localhost:9090']
    
  - job_name: 'node-exporter' # monitor node exporter 
    static_configs:
    - targets: ['165.227.105.59:9100']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']
